### ISSUE TITLE
Option to define where the database should be located.

### ISSUE THREAD

**Issue by EduardCM** [yeswework/fabrica-dev-kit#36]
Hello, 

Currently fdk creates the volume inside the docker VM, which isn't the best option if you want to have self contained projects that can be moved easily between machines. One can edited the docker-compose.yml file after the initial fdk setup and run it again with the --reinstall option, but its an unnecessary step that means re-downloading/installing everything.

It would be better if fdk checks if there's an existing docker-compose.yml file in the current directory and use that, or just have the ability to define a DB location inside the setup.yml file and go from there.

Thanks!

**Comment by tiojoca** [comment]
Thanks for the suggestion, we've changed the default `docker-compose.yml` to have the DB volume in a local path outside the container. We'll consider letting supporting a local/custom `docker-compose.yml` in the setup in the future.
