### ISSUE TITLE
[Fabrica] ⚠️  Docker containers provision failed.

### ISSUE THREAD

**Issue by alanef** [yeswework/fabrica-dev-kit#38]
`[Fabrica] 🏭  Bringing Docker containers up...
Creating network "test1_default" with the default driver
could not find an available, non-overlapping IPv4 address pool among the defaults to assign to the network
[Fabrica] ⚠️  Docker containers provision failed.`

Probably a config issue my side - but docker & docker-composer run normally for non Fabrica containers.  I have also stoppped all other containers and pruned networks so there no networks when I get this message?  Any ideas?

**Comment by tiojoca** [comment]
Can you try running `docker network ls`? Do you use a VPN?

**Comment by alanef** [comment]
Network ls was  none.  No VPN active.

**Comment by alanef** [comment]
Oops, my bad my VPN was enabled - not a good thing with docker - I normally have it disabled on my dev machine....  Issue sorted  ( turn off VPN )
