### ISSUE TITLE
Error setting up new project with 'fdk setup' command

### ISSUE THREAD

**Issue by auxcoder** [yeswework/fabrica-dev-kit#45]
After updating the Fabrica Dev Kit to version 3.1.6 and running a new project with `fdk setup` the following error arise

```
 => ERROR [ 6/14] RUN pecl -q install xdebug     && docker-php-ext-enable xdebug                                                                                               4.3s
------
 > [ 6/14] RUN pecl -q install xdebug     && docker-php-ext-enable xdebug:
#0 4.261 pecl/xdebug requires PHP (version >= 8.0.0, version <= 8.2.99), installed version is 7.4.33
 ```
 
 Not sure if the right next step is to change the image to a php `version >= 8.0.0, version <= 8.2.99` as shown in the log or specifying a different xdebug version.

**Comment by tiojoca** [comment]
Hi @auxcoder, thank you for reporting this issue.

We've release a new version with PHP set to 8.1 in the `Dockerfile`. I'm afraid you'll still have to manually update the version in the file for existing projects. You can find it in `provision/wp/Dockerfile`. Just change the first line to `FROM wordpress:php8.1-fpm` or replace the whole file for [the most recent version](https://github.com/yeswework/fabrica-dev-kit/blob/master/dev/provision/wp/Dockerfile).
